Add simple multiplication
fallnlove/sfastmatrixmult pull request #1
Opened 2024-01-10 15:52 UTC by fallnlove

-Added matrix.h
-Added simple_multiplication.h
-Added benchmarks

2024-01-12 14:20 UTC, DimaTrushin requested changes
В целом выглядит неплохо. Меня смутило что ты по-разному подключаешь google benchmarks и google tests. Это специально или нет?

В остальном только небольшие мелкие замечания.

Еще есть вопрос про переиспользование памяти в штрассене. Можно ли этого добиться?

2024-01-12 14:20 UTC, DimaTrushin commented on CMakeLists.txt
> +)
Я правильно понимаю, что google benchmark ты сделал через git submodule, а google tests через FetchContent? А почему не единообразно? И в чем разница между этими двумя подходами?

2024-01-12 14:20 UTC, DimaTrushin commented on tests/sources.cmake
> +)
Новая строчкав конце каждого файла. Не забывай проверять. А то git будет ругаться и пользхователь твоей библиотеки будет видеть эту ругань.

2024-01-12 14:20 UTC, DimaTrushin commented on bench/bench_strassen.cpp
> +static void BenchStrassen(benchmark::State& state) {
Когда что-либо определяешь в cpp файле обязательно определяй это в anonymous namespace.

2024-01-12 14:20 UTC, DimaTrushin commented on bench/bench_strassen.cpp
> +    std::mt19937 random_gen(random_device());
Я правильно понимаю, что это by design ты хочешь, чтобы каждый вызов был с одним и тем же детерминированным рандомом?

2024-01-12 14:20 UTC, DimaTrushin commented on bench/bench_strassen.cpp
> +    }
- Вот тут нарушение уровня абстракции. У тебя по хорошему должен быть метод, который позволяет матрицу инициализировать нужными случайными данными. Я бы ожидал тут код вида
```cpp
s_fast::Matrix<double> a = s_fast_Matrix<double>::Random(n, m, uniform(-1000, 1000));
```
- Вообще я бы делал using-ги в начале функции, чтобы не мучиться с namespace-ом. На уровне функции так делать можно.

2024-01-12 14:20 UTC, DimaTrushin commented on bench/bench_strassen.cpp
> +    for (auto _ : state) {
А это норм, что не по ссылке принимаешь аргументы из state? Не будет это проблемой? Они не тяжелые?

2024-01-12 14:20 UTC, DimaTrushin commented on bench/bench_strassen.cpp
> +        s_fast::Strassen(a, b);
А не будет ли оптимизирован у тебя этот цикл за счет того, что нет side effect?

2024-01-12 14:20 UTC, DimaTrushin commented on bench/bench_strassen.cpp
Очень хорошая тема с google benchmark

2024-01-12 14:20 UTC, DimaTrushin commented on bench/bench_strassen.cpp
> +    std::uniform_real_distribution<double> range_double(-1000., 1000.);
Магические константы, ты хочешь чтобы они у тебя у всех тестов были одинаковыми? Тогда я бы сделал так. Я бы завел один h файл со структурой содержащей статические constexpr параметры. И в начале тестирующей функции эти параметры присваивал бы локальным статическим constexpr параметрам. И в коде использовал бы локальные параметры. Тогда у тебя легко меняются глобальные параметры в одном месте и легко можно в любом тесте подкрутить свои параметры, если не подходят глобальные.

2024-01-12 14:20 UTC, DimaTrushin commented on bench/bench_simple_mult.cpp
> +static void BenchSimpleMultWithTranspose(benchmark::State& state) {
А у штрассена этого метода нет, потому что для него это не актуально или просто не делал еще?

2024-01-12 14:20 UTC, DimaTrushin commented on src/matrix.h
> +    Matrix() : rows_(0), columns_(0) {
1) Вместо такого подхода я бы сделал
```cpp
Matrix() = default;

size_t rows_ = 0;
size_t columns_ = 0;
```
2) Мне не нравится использовать size_t для размеров матриц. Это приведет тебя к проблемам с арифметическими операциями. В любом случае стоит в самом начале сделать публичные using-ги
```cpp
using Index = size_t;
// или
using Index = int64_t;
```
В этом случае ты везде вместо встроенного типа используешь Index и пользователи твоих матриц будут использовать его. И в случае если Index знаковый тебе не надо париться о порядке операций. Но придется ставить assert-ы. И еще надо быть аккуратным и не сравнивать знаковые и беззнаковые целые.
3) И еще у тебя одно из этих данных лишнее, потому что оно высчитывается из data_.size() и второго. Не знаю на сколько имеет смысл его хранить. Но это и не сложно.

2024-01-12 14:20 UTC, DimaTrushin commented on src/matrix.h
> +    size_t columns_;
Так как у тебя появились зависимые данные, то тебе надо предусмотреть правильное поведение move оператора. То есть надо сделать так
```cpp
Matrix(const Matrix&) = default;
Matrix(Matrix&&) noexcept : /*implementation*/{
}
Matrix& operator=(const Matrix&) = default;
Matrix& operator=(Matrix&&) noexcept {
  /*implementation*/
  return *this;
}
```
В противном случае после мува у тебя класс будет в некорректном состоянии.

2024-01-12 14:20 UTC, DimaTrushin commented on src/matrix.h
> +    Matrix(const std::vector<std::vector<T>>& matrix)
1) Плохая тема делать конструктор от конкретного контейнера. Дело в том, что кто-то может сюда поставить контейнер конвертируемый к твоему и это приведет к лишнему копированию данных. Кроме того, ты не можешь своровать данные ни в каком виде. Лучше сделай
```cpp
Matrix(std::initializer_list<std::initializer_list<double>> data);
```
И еще не забудь поставить assert-ы проверяющие что размеры всех матриц какие надо.
2) Плохое название для аргумента. Дело в том, что все таки аргумент не является структурой вида matrix, она является представлением сырого контейнера. Так лучше не делать. data будет лучше.

2024-01-12 14:20 UTC, DimaTrushin commented on src/matrix.h
> +            assert(matrix[row].size() == columns_);
Добавь тут сообщение об ошибке так
```cpp
assert(matrix[row].size() == columns_ && "All rows must have the same size!");
```

2024-01-12 14:20 UTC, DimaTrushin commented on src/matrix.h
> +    const T& operator()(size_t row, size_t column) const {
Если ты предполагаешь работу с double, то тут лучше сделать по-другому. Встроенные типы лучше возвращать by value, а уже тяжелые типы by reference. Для этого можно сделать класс helper, которые будет вычислять как возвращать. Например
```cpp
template<class T>
bool constexpr isArithmetic = std::is_arithmetic_v<T>;
template<class T, bool ByValue = isArithmetic<T>>
struct ReturnType;
template<class T, true>
struct ReturnType {
  using Type = T;
}
template<class T, false>
struct ReturnType {
  using Type T = const T&;
}
template<class T>
using ReturnAs = ReturnType<T>::Type;
```
И тогда ты можешь тут написать
```cpp
using ReturnElementType = ReturnAs<T>;

ReturnElementType operator()(Index row, Index column) const;
```
Опять же всякие шероховатости этого решения я оставляю на твое усмотрение.

2024-01-12 14:20 UTC, DimaTrushin commented on src/matrix.h
> +                (*this)(row, column) += other(row, column);
Ты можешь сделать цикл вида
```cpp
for(size_t i = 0; i < data_.size(); ++i) {
  data_[i] += other.data_[i]ж
}
```
Нет необходимости в таком сложном двойном цикле. Плюс не надо париться и думать как у тебя что хранится.

2024-01-12 14:20 UTC, DimaTrushin commented on src/matrix.h
> +    Matrix<T> Transpose() const {
Мне не очень нравится философия. Дело в том, что есть два типа методов: in place и out of place. Первые обычно могут быть сильно более эффективными и не аллоцируют новую память. Так вот я бы ожидал, что методы класса действуют inplace, а вот уже статические функции возвращают новые матрицы и реализованы на основе inplace методов. In place метод можно на основе std::swap реализовать.

2024-01-12 14:20 UTC, DimaTrushin commented on src/matrix.h
> +    // This function can be made more faster
much faster

2024-01-12 14:20 UTC, DimaTrushin commented on src/matrix.h
> +    Matrix<T> GetSubMatrix(std::pair<size_t, size_t> begin, std::pair<size_t, size_t> end) const {
Не используй std::pair. Дело в том, что не понятно что значат first и second. Лучше создай свою структуру
```cpp
struct Position {
  Index row;
  Index column;
}
```
И тогда пользователь будет понимать что значат поля.

2024-01-12 14:20 UTC, DimaTrushin commented on src/matrix.h
> +    Matrix<T> GetSubMatrix(std::pair<size_t, size_t> begin, std::pair<size_t, size_t> end) const {
А не хочешь иметь возможность возвращать константный view объект?

2024-01-12 14:20 UTC, DimaTrushin commented on src/matrix.h
> +    Matrix<T> GetSubMatrix(std::pair<size_t, size_t> begin, std::pair<size_t, size_t> end) const {
У тебя название обманывает. End обычно обозначает позицию за последним элементом, а у тебя это вточности последний элемент. Тогда лучше другое название использовать.

2024-01-12 14:20 UTC, DimaTrushin commented on src/matrix.h
> +Matrix<T> operator+(const Matrix<T>& lhs, const Matrix<T>& rhs) {
- Если хочешь оптимизацию, то имеет смысл сделать все четыре версии
```cpp
Matrix<T> operator+(const Matrix<T>& lhs, const Matrix<T>& rhs);
Matrix<T> operator+(Matrix<T>&& lhs, const Matrix<T>& rhs);
Matrix<T> operator+(const Matrix<T>& lhs, Matrix<T>&& rhs);
Matrix<T> operator+(Matrix<T>&& lhs, Matrix<T>&& rhs);
```
Тогда по Matrix<T>&& аргументу можно не делать копии, а переиспользовать его данные.
- И я предпочитаю эти функции делать friend методами. Тогда это позволяет делать неявную конвертацию типов в выражениях. Но это уже вопрос дизайна.

2024-01-12 14:20 UTC, DimaTrushin commented on src/simple_multiplication.h
> +                tmp += lhs(row, i) * rhs(i, column);
А почему не
```cpp
result(row, column) += lhs(row, i) * rhs(i, column);
```
?? Зачем вводить tmp? Ты же уже нулем инициализировал матрицу.

2024-01-12 14:20 UTC, DimaTrushin commented on src/strassen.h
> +std::vector<Matrix<T>> GetSubMatrixes(const Matrix<T>& matrix) {
1) А не будет ли выгоднее возращать view объекты на подматрицы? Мы же все равно не должны трогать эти подблоки. Или ты их память будешь переиспользовать?
2) Вместо std::vector лучше создать структуру с нужными именами полей, чтобы было удобнее использовать. Тут проблема аналогичная std::pair. Поля вектора ничего тебе не говорят какой имнно блок у тебя и что он значит.

2024-01-12 14:20 UTC, DimaTrushin commented on src/strassen.h
> +void SetSubMatrix(Matrix<T>& to, const Matrix<T>& from, std::pair<size_t, size_t> begin) {
Если ты используешь входные и выходные параметры, то
1) входные параметры всегда должны идти до выходных
2) выходные параметры лучше передавать by pointer, чтобы было понятно, что мы будем менять аргумент.

2024-01-12 14:20 UTC, DimaTrushin commented on src/strassen.h
> +
Для удобства в начале можно сделать так
```cpp
using namespace detail;
```

2024-01-12 14:20 UTC, DimaTrushin commented on src/strassen.h
> +namespace detail {
Я предпочитаю делать разные namespace. Потому что detail могут быть много в разных единицах трансляции и они могут пересечься.

2024-01-12 14:20 UTC, DimaTrushin commented on src/strassen.h
> +    std::vector<Matrix<T>> lhs_sub_mat = std::move(detail::GetSubMatrixes(lhs));
Тут не надо std::move. У тебя и так справа от = будет rvalue объект. Кроме того, ты этим делом мешаешь rvo затригериться и у тебя будет move вместо инициализации.

2024-01-12 14:20 UTC, DimaTrushin commented on src/strassen.h
> +        Strassen(lhs_sub_mat[0] + lhs_sub_mat[3], rhs_sub_mat[0] + rhs_sub_mat[3]));
Судя по алгоритмы тебе тут нужны только view объекты, тебе не надо было копировать матрицы. Только надо тогда уметь брать подматрицы у view матриц. И видимо алгоритм надо от view объектов сделать.

2024-01-12 14:20 UTC, DimaTrushin commented on src/strassen.h
> +    tmp_matrixes.reserve(7);
Можно ли сразу зарезервировать место для результата и все эти временные матрицы создать по адресу этого результата и переиспользовать эту память во всех рекурсивных вызовах?

2024-01-12 14:20 UTC, DimaTrushin commented on src/strassen.h
> +    Matrix<T> res(lhs.Rows(), rhs.Columns());
ну почему не result?

2024-01-12 14:20 UTC, DimaTrushin commented on tests/test_strassen.cpp
> +        }
Сделай статический метод случайной инициализации, чтобы тут не делать мелкую работу.

2024-01-12 14:20 UTC, DimaTrushin commented on tests/test_strassen.cpp
> +constexpr size_t kIters = 10;
1) Заверни в anonimous namespace
2) Вообще говоря, есть способ в google tests хранить общую информацию между тестам или между их вызовами. Посмотри как это делается, чтобы не делать таких глобальных данных.

2024-01-12 14:20 UTC, DimaTrushin commented on tests/utils.h
> +bool IsEqualMatrix(const s_fast::Matrix<T>& lhs, const s_fast::Matrix<T>& rhs) {
Во-первых, надо сделать operator== и operator!= для матриц. Это избавит тебя от необходимости использовать этот метод.
Во-вторых, ты можешь сделать так
```cpp
return lhs.Rows() == rhs.Rows() && lhs.Columns() == rhs.Columns() && lhs.data_ == rhs.data_;
```
Нет необходимости имплементировать равенство векторов заново. =)

2024-01-24 22:12 UTC, playerr17 commented on CMakeLists.txt
> +)
Лучше все сделаю через FetchContent, так будет легче, не нужно лишние команды в гите вводить

2024-01-29 19:01 UTC, playerr17 commented on bench/bench_simple_mult.cpp
> +static void BenchSimpleMultWithTranspose(benchmark::State& state) {
Для Штрассена это не актуально, потому что, когда мы опускаемся до уровня, когда явно перемножаем матрицы, то там все матрицы и так в кеше полностью лежат

2024-01-29 20:28 UTC, playerr17 commented on bench/bench_strassen.cpp
> +    for (auto _ : state) {
Они вроде не тяжелые, там под капотом просто лист длины равной количеству итераций

2024-02-14 22:43 UTC, fallnlove commented on src/strassen.h
> +    tmp_matrixes.reserve(7);
Ну не очень, там всякие зависимости этих матриц есть, оно складываются и вычитаются

2024-02-14 22:44 UTC, fallnlove commented on src/strassen.h
> +        Strassen(lhs_sub_mat[0] + lhs_sub_mat[3], rhs_sub_mat[0] + rhs_sub_mat[3]));
Ну вот я переписал на View и чет теперь оно жутко тормозит, как будто прошлое было быстрее намного

2024-03-25 14:55 UTC, DimaTrushin requested changes
Добавил еще несколько комментариев.

2024-03-25 14:55 UTC, DimaTrushin commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
решил откатиться на c++17?

2024-03-25 14:55 UTC, DimaTrushin commented on src/view_matrix_helper.h
> +using IfConst = std::conditional_t<IsConst, T, Y>;
Что-то тут какая-то хрень написана. Ты просто перегрузил conditional_t в виде чего-то более запутанного. Твое название IfConst врет, дело в том, что у тебя НЕ проверяется условие константности, то есть я бы ожидал что у тебя будет 3 типа съедаться и первый проверяется на наличие const квалификатора, но ты вместо этого просто передаешь bool, который может принимать любые значения никак не связанные с константностью чего-либо. То есть название шаблона максимально нагло врет. Это обычный IfElse

2024-03-25 14:55 UTC, DimaTrushin commented on src/view_matrix_helper.h
Вообще этот файл выглядит странным. Почему он  только для view_matrix предназначен? Если он нужен только для специального класса и только внутри него используется, то можно в cpp файле объявить нужные методы в anonymous namespace. А если они не только в одном классе используются, то почему это не глобальные хелперы?

2024-03-25 14:55 UTC, DimaTrushin commented on src/view_matrix.h
> +template <class T, bool IsConst>
Не очень понятно за что отвечает IsConst параметр. Что именно константное? Через view нельзя менять элементы? Это как const_iterator?

Еще один вариант, как это можно было бы сделать. Можно сделать базовый класс с using-ами и подключать нужный.
```cpp
template<class T>
struct DefinesConst {
  using Data = std::remove_cv_t<T>;
  using Ref = const Data&;
};
template<class T>
struct DefinesNonConst {
  using Data = std::remove_cv_t<T>;
  using Ref = Data&;
};
```
И потом тут сделать базовый класс в виде шаблона
```cpp
template<class T, class Defines>
class RawViewMatrix : public Defines {};
```
И тогда у тебя все дефайны подтянутся какие нужно. А потом уже делаешь различные специализации.

2024-03-25 14:55 UTC, DimaTrushin commented on src/view_matrix.h
> +    Position end_;
1) Помести все данные в конец класса, чтобы их не искать по телу класса.
2) Замени MatrixType& на std::reference_wrapper<MatrixType>. Тогда у тебя View будет иметь value semantics, ее можно будет копировать и мувать.

2024-03-25 14:55 UTC, DimaTrushin commented on src/view_matrix.h
> +        return std::min(Rows(), matrix_.Rows() - begin_.row);
Тебе разрешено делать View которая выходит за границы матрицы? Зачем такой дизайн?

2024-03-25 14:55 UTC, DimaTrushin commented on src/view_matrix.h
> +        assert(begin_.row + row < matrix_.Rows() && begin_.column + column < matrix_.Columns());
А не надо проверить row и column на положительность? У тебя же не гарантируется беззнаковость Index.

2024-03-25 14:55 UTC, DimaTrushin commented on src/view_matrix.h
> +    ConstReturnElementType operator()(Index row, Index column) const {
Ага, ты хочешь обрамить матрицу нулями снаружи, если я правильно понял.

2024-03-25 14:55 UTC, DimaTrushin commented on src/view_matrix.h
> +    }
По хорошему эти два метода можно объединить в один шаблонный
```cpp
template<class TMatrix>
RawViewMatrix& operator+=(const TMatrix& other) {
  // implementation
}
```
Ведь тебе пофигу какие там коэффициенты и что там внутри, тебе главное уметь обращаться с помощью оператора operator() к элементам i, j.

2024-03-25 14:55 UTC, DimaTrushin commented on src/view_matrix.h
> +    RawViewMatrix<T, IsConst>& operator+=(const RawViewMatrix<T, IsConst>& other) {
Внутри шаблонного класса его имя можно использовать без параметров и писать просто RawViewMatrix.

2024-03-25 14:55 UTC, DimaTrushin commented on src/view_matrix.h
> +    inline friend Matrix<T> operator+(const RawViewMatrix<T, IsConst>& lhs,
А почему эти методы в приватной части? И еще не нужны шаблонные параметры для RawViewMatrix. И еще кажется не нужно inline в этом месте (но что-то я не уверен).

2024-03-25 14:55 UTC, DimaTrushin commented on src/view_matrix.h
> +          end_(end.row == -1 ? Position{matrix.Rows(), matrix.Columns()} : end) {
А что если у тебя один параметр -1, а второй положительный? Я бы сделал отдельно для строк и столбцов отдельный метод выставления позиции.

2024-03-25 14:55 UTC, DimaTrushin commented on src/view_matrix.h
> +        return result;
Мне не нравится дублирование кода. Я бы ожидал что-то вроде
```cpp
Matrix<T> result(lhs.Rows(), lhs.Columns());
RawViewMatrix resultView = result;
resultView += rhs;
return result;
```

2024-03-25 14:55 UTC, DimaTrushin commented on src/view_matrix.h
> +        if (lhs.Rows() != rhs.Rows() && lhs.Columns() != rhs.Columns()) {
здесь же надо ||

2024-03-25 14:55 UTC, DimaTrushin commented on src/view_matrix.h
> +Matrix<T> GetMatrix(const ConstViewMatrix<T>& view_matrix) {
Дублирование кода. Тебе надо сделать возможным кастовать ViewMatrix к ConstViewMatrix и сделать лишь одну версию этой функции, которая принимает ConstViewMatrix.

2024-03-25 14:55 UTC, DimaTrushin commented on src/utils.h
> +inline Index GetNearestPowerOfTwo(Index number) {
Только это не nearest, это первая большая чем number степень двойки.

2024-03-25 14:55 UTC, DimaTrushin commented on src/strassen.h
>      if (std::min({lhs.Rows(), lhs.Columns(), rhs.Columns()}) <= 8) {
Тебя не смущает волшебная константа 8?

2024-03-25 14:55 UTC, DimaTrushin commented on src/strassen.h
> +    auto lhs_sub = GetSubMatrixes<const ConstViewMatrix<T>, ConstViewMatrix<T>>(lhs);
Что-то тут слишком сложная игра с шаблонами идет. Зачем тут такие странные явные параметры для функции? Зачем const для первого аргумента? В этом есть смысл?

2024-03-25 14:55 UTC, DimaTrushin commented on src/matrix.h
> +        other.columns_ = 0;
Это можно сократить
```cpp
Matrix(Matrix&& other) noexcept : data_(std::move(other.data_)), columns_(std::exchange(other.columns_, 0)) {}
```

2024-03-25 14:55 UTC, DimaTrushin commented on src/matrix.h
> +        other.columns_ = 0;
Если ты сделаешь мув матрицы в себя, то ты сломаешь инвариант в этой строчке. Не забывай про все случаи. То есть код должен корректно работать всегда, и быстро в частых случаях.
Замени на
```cpp
columns_ = std::exchange(other.columns_, 0);
```

2024-03-25 14:55 UTC, DimaTrushin commented on src/matrix.h
> +        assert(row < Rows() && column < Columns());
тебе еще надо проверять на положительность.

2024-03-25 14:55 UTC, DimaTrushin commented on src/matrix.h
> +    Matrix<T> GetSubMatrix(Position begin, Position end) const {
А точно ли нужен этот метод, если у тебя есть ViewMatrix?

2024-03-25 14:55 UTC, DimaTrushin commented on src/matrix.h
> +        Matrix<T> tmp(lhs);
Здесь надо добавить move
```cpp
Matrix tmp = std::move(lhs);
```
И не используй внутри класса его имя с параметрами.

2024-03-25 14:55 UTC, DimaTrushin commented on src/matrix.h
> +        return tmp;
Тут можно написать
```cpp
return std::move(rhs) + lhs;
```

2024-03-25 14:55 UTC, DimaTrushin commented on src/matrix.h
> +    friend Matrix<Y> SimdMultiplication(const Matrix<Y>&, const Matrix<Y>&);
А зачем тут Y? Ты хочешь чтобы метод для матриц над даблами мог залезть во внутренности матриц с любыми коэффициентами?

2024-03-25 14:55 UTC, DimaTrushin commented on src/matrix.h
> +    std::mt19937 random(std::chrono::high_resolution_clock::now().time_since_epoch().count());
НИКОГДА так НЕ делай. Не инициализируй рандом временем системы. Потому что ты получаешь не контролируемое и не тестируемое состояние при каждом запуске. Если у тебя случится баг, то ты его НЕ отловишь при следующем запуске. Сделай класс Random, который умеет возвращать что надо и храни все внутренности внутри него. А для этого метода тогда уж создай как минимум статическую переменную в этом методе, или если уж на то пошло, спрячь в виде приватного singleton-а внутрь Matrix класса этот Random. Но НЕ делай так.

2024-03-25 14:55 UTC, DimaTrushin commented on src/simd_multiplication.h
А где происходят настройки уровня симдов?

2024-04-08 21:07 UTC, fallnlove commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
Да, тут с 20 стандарта ничего не используется, чтобы у людей не требовало компилятор 20, вернулся на 17

2024-04-08 21:08 UTC, fallnlove commented on src/simd_multiplication.h
Где-то в xsimd :)

2024-05-07 14:37 UTC, merged

2024-05-20 20:34 UTC, DimaTrushin reviewed
Сделал еще пару мелких замечаний

2024-05-20 20:34 UTC, DimaTrushin commented on src/view_matrix_helper.h
> +using ReturnIfConst = IfElse<IsConst, helper::ReturnAs<T>, T&>;
Очень странное название для шаблона. Не понятно, что эта штука делает.

2024-05-20 20:34 UTC, DimaTrushin commented on src/view_matrix.h
> +    MatrixType& matrix_;
А почему не std::reference_wrapper<MatrixType>? Тогда у тебя будет value semantics и гарантируется, что эта штука не nullptr. Не делай поля ссылки в классе.

2024-05-20 20:34 UTC, DimaTrushin commented on src/view_matrix.h
> +    RawViewMatrix(ViewMatrixType& matrix, Position begin = {0, 0}, Position end = {-1, -1})
А тут почему не const ViewMatrixType&? Просто тут rvalue нельзя подставить. Ну и ты не должен менять аргумент конструктора.

2024-05-20 20:34 UTC, DimaTrushin commented on src/view_matrix.h
> +
Я бы на твоем месте все остальные методы (copy constructor, copy assignment, move constructor, move assignment) удалил. А то из-за ссылки в теле класса у тебя тут черт знает что происходит.

2024-05-20 20:34 UTC, DimaTrushin commented on src/simd_multiplication.h
> +                result(row, column) += xsimd::reduce_add(lhs_vec * rhs_vec);
Вот тут можно накапливать не сразу в результат а в промежуточный xsimd аргумент. А потом уже в конце сделать один reduce_add, может получиться подругому по скорости. Я думаю, что будет быстрее, но не знаю на сколько ощутимо.

2024-05-20 20:34 UTC, DimaTrushin commented on src/matrix.h
> +Matrix<T> Random(typename Matrix<T>::Index rows, typename Matrix<T>::Index columns,
Это плохой рандомный генератор. Ты не можешь гарантировать распределение между вызовами этой функции. Лучше делать генератор std::mt19937 статическим.

2024-05-20 20:34 UTC, DimaTrushin commented on src/matrix.h
> +    inline friend Matrix<T> operator+(const Matrix<T>& lhs, const Matrix<T>& rhs) {
Лишнее inline.

2024-05-20 20:34 UTC, DimaTrushin commented on src/matrix.h
> +        return tmp;
А почему ты не сослался на другую имплементацию?

2024-05-20 20:34 UTC, DimaTrushin commented on src/matrix.h
> +    inline friend Matrix<T> operator+(const Matrix<T>& lhs, const Matrix<T>& rhs) {
А почему функции объявлены в приватной части?

2024-05-20 20:34 UTC, DimaTrushin commented on src/matrix.h
> +    inline friend Matrix<T> operator-(const Matrix<T>& lhs, Matrix<T>&& rhs) {
Не хватает пробелов между функциями.